// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPIcJ9xINhLmm65GBBODS5KyqGfedoKyI',
    appId: '1:314552752091:web:29ecb32de834ad7423b9fe',
    messagingSenderId: '314552752091',
    projectId: 'rate-io',
    authDomain: 'rate-io.firebaseapp.com',
    databaseURL: 'https://rate-io-default-rtdb.firebaseio.com',
    storageBucket: 'rate-io.appspot.com',
    measurementId: 'G-WB50HG2WE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLAX2nVlJ1_PeuRahemGj15mefq9sTYkw',
    appId: '1:314552752091:android:7d9dbab6a051d45b23b9fe',
    messagingSenderId: '314552752091',
    projectId: 'rate-io',
    databaseURL: 'https://rate-io-default-rtdb.firebaseio.com',
    storageBucket: 'rate-io.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACv8eWy3A7P--yPcE-phiDNgxd58fQ48Y',
    appId: '1:314552752091:ios:c9c0c0d13915e7f723b9fe',
    messagingSenderId: '314552752091',
    projectId: 'rate-io',
    databaseURL: 'https://rate-io-default-rtdb.firebaseio.com',
    storageBucket: 'rate-io.appspot.com',
    iosBundleId: 'com.example.rateIo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACv8eWy3A7P--yPcE-phiDNgxd58fQ48Y',
    appId: '1:314552752091:ios:c9c0c0d13915e7f723b9fe',
    messagingSenderId: '314552752091',
    projectId: 'rate-io',
    databaseURL: 'https://rate-io-default-rtdb.firebaseio.com',
    storageBucket: 'rate-io.appspot.com',
    iosBundleId: 'com.example.rateIo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPIcJ9xINhLmm65GBBODS5KyqGfedoKyI',
    appId: '1:314552752091:web:a749c004e29f58eb23b9fe',
    messagingSenderId: '314552752091',
    projectId: 'rate-io',
    authDomain: 'rate-io.firebaseapp.com',
    databaseURL: 'https://rate-io-default-rtdb.firebaseio.com',
    storageBucket: 'rate-io.appspot.com',
    measurementId: 'G-WTTVQ1RD7F',
  );
}
